# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_UNIT_TESTS="yes"
    - INSTALL_MEMCACHE="yes"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: 7.1
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: 7.2
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
    - php: nightly
      env: INSTALL_APCU="yes" INSTALL_MEMCACHE="no"
  allow_failures:
    - php: 7.2
    - php: nightly

services:
  - memcache
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then bash build/travis/unit-tests.sh $PWD; fi

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml; fi

branches:
  except:
    - 2.5.x
