<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_media
 *
 * @copyright   Copyright (C) 2005 - 2017 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace Joomla\Component\Media\Administrator\View\Plugin;

defined('_JEXEC') or die;

use Joomla\CMS\View\HtmlView;

/**
 * Media List View
 *
 * @since  __DEPLOY_VERSION__
 */
class Html extends HtmlView
{
	protected $data = null;

	/**
	 * @param null|string $tpl
	 *
	 * @return string
	 */
	public function display( $tpl = null ) {
		$this->data = $this->get("Data");

		return parent::display($tpl); // TODO: Change the autogenerated stub
	}


}