export const SELECT_DIRECTORY = 'SELECT_DIRECTORY';

// Api handlers
export const LOAD_CONTENTS_SUCCESS = 'LOAD_CONTENTS_SUCCESS';

// Create folder modal
export const SHOW_CREATE_FOLDER_MODAL = 'SHOW_CREATE_FOLDER_MODAL';
export const HIDE_CREATE_FOLDER_MODAL = 'HIDE_CREATE_FOLDER_MODAL';